/* 範例資料：十二層產業範例公司 + 台積電、SpaceX 研究卡
   財報數字來自公司公告（日期見各欄來源）；標示「示範」者為說明填法用的假設，不是事實或建議。 */
window.EXAMPLES = {
  version: 1,
  layers: [
    'Microsoft（Copilot）、Meta（廣告變現）、Salesforce、Adobe、Palantir',
    'OpenAI、Anthropic（未上市）、Google DeepMind（GOOGL）、Meta、xAI（併入 SpaceX／SPCX）',
    'Microsoft Azure、AWS（AMZN）、Google Cloud、Oracle、CoreWeave',
    '鴻海 2317、廣達 2382、緯創 3231、緯穎 6669、Dell、Supermicro',
    'Broadcom、Arista、Marvell、智邦 2345、Coherent、Lumentum',
    '台達電 2308、奇鋐 3017、雙鴻 3324、Vertiv、Eaton、GE Vernova',
    'NVIDIA、AMD、Broadcom（客製 ASIC）、聯發科 2454、世芯-KY 3661',
    'SK hynix、Samsung、Micron',
    '台積電 2330（CoWoS）、日月光投控 3711、Amkor、弘塑 3131',
    '台積電 2330、Samsung Foundry、Intel Foundry',
    'ASML、Applied Materials、Lam Research、Tokyo Electron、KLA',
    '環球晶 6488、信越化學、SUMCO、欣興 3037、南電 8046',
  ],
  positions: [
    { company: '台積電 2330', layer: '10 晶圓代工', revenueFrom: '第 7 層晶片設計（NVIDIA、AMD、Broadcom）的投片支出', capacityBy: '第 11 層設備（EUV）、第 9 層先進封裝產能', leading: '雲端四大資本支出、CoWoS 月產能、月營收', updated: '2026-09-29' },
    { company: 'SpaceX SPCX', layer: '2 模型與 AI 實驗室', revenueFrom: 'Starlink 用戶訂閱、政府與商業發射、xAI 模型服務', capacityBy: '第 3 層算力（自建資料中心）、第 6 層電力', leading: 'Starlink 用戶數、AI 部門資本支出、星艦試飛進度', updated: '2026-09-29' },
  ],
  cards: [
    {
      example: true, code: '2330', name: '台積電', market: '台股', layer: '10 晶圓代工', date: '2026-09-29', price: '2475',
      lights: [
        { c: '綠', note: '先進製程＋CoWoS 雙重瓶頸，HPC 佔 2Q26 營收 66%' },
        { c: '綠', note: '毛利率 67.7%、營益率 60.3%，年增約 9～11 個百分點' },
        { c: '綠', note: '全年美元營收成長上修至「略高於 40%」（原近 30%）' },
        { c: '黃', note: '示範假設下約 23 倍 2026 預估本益比，已反映高成長' },
        { c: '黃', note: '示範：請依實際均線、RSI 填寫' },
        { c: '黃', note: '示範：請依外資、投信近 20 日買賣超填寫' },
      ],
      fin: [
        { cur: '1270.38', prev: '933.79', src: '新台幣十億元｜2Q26 vs 2Q25 法說新聞稿（2026-07-16、2025-07-17）' },
        { cur: '67.7', prev: '58.6', src: '同上' },
        { cur: '60.3', prev: '49.6', src: '同上' },
        { cur: '27.25', prev: '15.36', src: '新台幣元，稀釋 EPS' },
        { cur: '', prev: '', src: '待補：2Q26 財報現金流量表（公開資訊觀測站）' },
        { cur: '', prev: '', src: '待補：營業現金流 − 資本支出' },
        { cur: '', prev: '', src: '待補；全年指引 600～640 億美元' },
        { cur: '', prev: '', src: '待補：資產負債表' },
      ],
      finGap: '淨利年增 77.4% 遠高於營收年增 36.0%，主因毛利率大幅擴張。3Q26 毛利率指引 65～67% 低於 2Q26，需確認是匯率與海外廠稀釋，而不是需求轉弱。',
      guidance: '3Q26 營收 446～458 億美元（匯率假設 1 美元兌 32 元）；毛利率 65～67%；營益率 56～58%。\n全年美元營收成長上修至略高於 40%；2026 資本支出 600～640 億美元（70～80% 先進製程、10～20% 先進封裝）。\n2026 全年股利預估每股 24 元。',
      quotes: '示範填法：「日期｜說話者｜原話」，例如「2026-07-16｜法說會｜（貼上管理層對 AI 需求的原話）」。只貼原文，不改寫。',
      qa: '示範重點：海外廠毛利稀釋幅度、2 奈米量產與客戶導入、CoWoS 擴產時程、關稅與匯率影響。',
      assumptions: '示範：1Q26 EPS 約 22.1 元（由 2Q26 淨利季增 23.4% 回推）＋2Q26 27.25 元，下半年每季約 28～30 元，2026 全年 EPS 約 107 元。',
      val: [
        { assume: '示範：2026 預估 EPS 107 元 × 22 倍本益比', fair: '2354', note: '本益比取近年區間上緣' },
        { assume: '示範：WACC 9%、5 年營收年複合成長 20%、永續成長 3%', fair: '2600', note: '對毛利率假設很敏感' },
        { assume: '請查詢最新分析師共識目標價', fair: '', note: '' },
      ],
      valCheck: '兩法差約 10%，差距主要來自長期成長假設；最脆弱的是「毛利率維持 65% 以上」這一條。',
      tech: [
        { read: '', judge: '示範：收盤站上 20／60 日均線且均線向上＝多頭排列' },
        { read: '', judge: '示範：RSI > 70 過熱、< 30 超賣' },
        { read: '', judge: '' }, { read: '', judge: '' }, { read: '', judge: '' }, { read: '', judge: '' }, { read: '', judge: '' },
      ],
      chip: [
        { d5: '', d20: '', judge: '示範：外資是台積電籌碼主力，連續賣超要留意' },
        { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' },
        { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' },
      ],
      verdict: '【範例】AI 供應鏈最核心的瓶頸，體質與指引都是綠燈；估值已不便宜，關鍵在毛利率能否守住 65% 以上。',
      thesis: '先進製程與先進封裝雙寡占，HPC／AI 需求同時推升營收與毛利率。第 3 層雲端資本支出是它的領先指標。',
      wrongIf: '毛利率連續兩季低於 60%；或主要雲端業者下修資本支出；或 3／2 奈米市占流失。',
      action: '【範例，不構成建議】分批布局，單一個股不超過總資產 10%，張數用「策略」頁的部位計算器決定。',
      monitored: '否',
    },
    {
      example: true, code: 'SPCX', name: 'SpaceX', market: '美股', layer: '2 模型與 AI 實驗室', date: '2026-09-29', price: '148.52',
      lights: [
        { c: '綠', note: '發射寡占＋Starlink 連網＋xAI 模型，三條業務線' },
        { c: '紅', note: '仍虧損；上半年資本支出 285 億美元，自由現金流大幅為負' },
        { c: '黃', note: '首份季報（2026-08-04）未提供前瞻指引' },
        { c: '紅', note: '市值約 1.9 兆美元，年化營收約 313 億，股價營收比約 60 倍' },
        { c: '黃', note: 'IPO 價 135 → 高點 211 → 7 月約 123 → 9/29 約 148' },
        { c: '黃', note: '閉鎖期：其他投資人 180 天（約 12 月起分批）、內部人 366 天' },
      ],
      fin: [
        { cur: '7814', prev: '4071', src: '百萬美元｜2Q26 財報 8-K（2026-08-04）' },
        { cur: '', prev: '', src: '未揭露' },
        { cur: '-1.8', prev: '-23.8', src: '營業損失 1.43 億 ÷ 營收（自行計算）；去年 9.70 億' },
        { cur: '-0.09', prev: '', src: '美元，基本／稀釋 EPS' },
        { cur: '3466', prev: '', src: '上半年累計（百萬美元）' },
        { cur: '-25010', prev: '', src: '上半年：營業現金流 3,466 − 資本支出 28,476（自行計算）' },
        { cur: '18369', prev: '', src: '2Q26 單季（百萬美元）' },
        { cur: '', prev: '', src: '待補' },
      ],
      finGap: '調整後 EBITDA 35.4 億美元（年增 191%）看起來亮眼，但單季資本支出 184 億美元，自由現金流大幅為負；靠 IPO 募資約 857 億美元與 250 億美元公司債支應。',
      guidance: '首份季報未提供第三季或全年指引。\n分部：Connectivity（Starlink）營收 42.9 億、營業利益 16.6 億；AI 營收 25.6 億（年增 247%）、營業損失 12.6 億；Space 營收 9.6 億、營業損失 5.4 億（百萬美元換算為億）。\nStarlink 用戶 1,200 萬（年增一倍）。',
      quotes: '示範填法：「日期｜說話者｜原話」，只貼財報電話會議的原文。',
      qa: '示範重點：AI 部門資本支出何時見頂、Starlink 每用戶營收（ARPU）走勢、星艦商業化時程、閉鎖期解禁安排。',
      assumptions: '示範：流通股數以 IPO 估值 1.77 兆 ÷ 135 美元 ≈ 131 億股估算；年化營收 = 2Q26 × 4 ≈ 313 億美元。',
      val: [
        { assume: '示範：年化營收 313 億 × 40 倍股價營收比 ÷ 131 億股', fair: '95.5', note: '40 倍已是高成長股上緣' },
        { assume: '示範：高度依賴星艦與 AI 假設，區間極寬，建議只做情境分析', fair: '', note: '' },
        { assume: '請查詢最新分析師共識目標價', fair: '', note: '' },
      ],
      valCheck: '市價遠高於示範的相對估值，代表市場在為 Starlink 與 AI 的長期選擇權付費；最脆弱的假設是 AI 部門能否轉為正現金流。',
      tech: [
        { read: '135 → 211 → 約 123 → 148.52', judge: 'IPO 後大漲大跌，尚未形成明確趨勢' },
        { read: '', judge: '' }, { read: '', judge: '' }, { read: '', judge: '' }, { read: '', judge: '' },
        { read: '', judge: '示範：IPO 價 135 美元可視為重要支撐參考' }, { read: '', judge: '' },
      ],
      chip: [
        { d5: '', d20: '', judge: '美股無三大法人資料，可改看機構持股（13F）' },
        { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' }, { d5: '', d20: '', judge: '' },
        { d5: '', d20: '', judge: '已納入 Nasdaq-100，指數基金被動買盤' },
        { d5: '', d20: '', judge: '閉鎖期解禁前後留意賣壓' },
      ],
      verdict: '【範例】成長與題材很強，但仍在大量燒錢、估值極高，屬高風險、高波動部位。',
      thesis: 'Starlink 已經獲利（Connectivity 營業利益 16.6 億美元）＋AI 營收三位數成長；關鍵在未來能否用自有現金流支應資本支出。',
      wrongIf: 'Starlink 用戶年增降到 30% 以下；或 AI 部門虧損持續擴大；或閉鎖期解禁後股價跌破 IPO 價。',
      action: '【範例，不構成建議】若要參與，部位上限 3%，停損以固定風險法計算。',
      monitored: '否',
    },
  ],
};
